pool:
  vmImage: 'Ubuntu 16.04'

pr:
  branches:
    include:
    - master

trigger:
  branches:
    include:
    - master
  
variables:
  buildConfiguration: 'Release'

steps:
# Install SonarScanner
- script: |
    dotnet tool install --global dotnet-sonarscanner

# Begin SonarScanner
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner begin /k:"$(SONAR_PROJECT_KEY)" /d:sonar.organization="$(SONAR_ORGANIZATION)" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)" /v:"$(buildId)" /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml"

- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test --configuration $(buildConfiguration) --no-build

# End SonarScanner
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
